#! /bin/sh

# When `ttalk-sh' fails, run this and it won't fail anymore.  Make sure it
# is not really a failure first!

if test -z "$srcdir"; then
    srcdir=.
fi
if test ! -f "${srcdir}/ttalk-o"; then
    srcdir=src
fi
if test ! -f "${srcdir}/ttalk-o"; then
    echo "You must chdir to this script's directory before running it.";
    exit 77;
fi
if test -z "$top_builddir"; then
    top_builddir=..
fi
if test ! -f "${top_builddir}/src/tparser"; then
    top_builddir=.
fi
if test ! -f "${top_builddir}/src/tparser"; then
    echo "You must chdir to this script's directory before running it.";
    exit 77;
fi

rm ${srcdir}/ttalk-o
${top_builddir}/src/tparser any three args < ${srcdir}/ttalk-in > ${srcdir}/ttalk-o
