#! /bin/sh
# the next line restarts using wish \
exec wish "$0" "$@"

# interface generated by SpecTcl version 1.1 from /home/davidc/Conx/conxv/src/simple.ui
#   root     is the parent window for this user interface

proc simple_ui {root args} {

	# this treats "." as a special case

	if {$root == "."} {
	    set base ""
	} else {
	    set base $root
	}
    
	frame $base.the_frame


	# Geometry management

	grid $base.the_frame -in $root	-row 1 -column 1  \
		-sticky nesw

	# Resize behavior management

	grid rowconfigure $root 1 -weight 1 -minsize 30
	grid columnconfigure $root 1 -weight 1 -minsize 30
# additional interface code
tconx_simple_initialize $root

# end additional interface code

}


# Allow interface to be run "stand-alone" for testing

catch {
    if [info exists embed_args] {
	# we are running in the plugin
	simple_ui .
    } else {
	# we are running in stand-alone mode
	if {$argv0 == [info script]} {
	    wm title . "Testing simple_ui"
	    simple_ui .
	}
    }
}
