#! /bin/sh
# the next line restarts using wish \
exec wish "$0" "$@"

# interface generated by SpecTcl version 1.1 from /home/davidc/Conx/conxv/src/slider.ui
#   root     is the parent window for this user interface

proc slider_ui {root args} {

	# this treats "." as a special case

	if {$root == "."} {
	    set base ""
	} else {
	    set base $root
	}
    
	frame $base.frame#2

	frame $base.the_frame

	frame $base.frame#3

	frame $base.frame#4

	frame $base.frame#5

	label $base.label#1 \
		-text lowval
	catch {
		$base.label#1 configure \
			-font -*-Courier-Medium-R-Normal-*-*-120-*-*-*-*-*-*
	}

	scale $base.scale#1 \
		-command "tconx_slider_scale_motion $root" \
		-label Value \
		-orient h \
		-variable "$base.scale_var"

	label $base.label#2 \
		-text highval
	catch {
		$base.label#2 configure \
			-font -*-Courier-Medium-R-Normal-*-*-120-*-*-*-*-*-*
	}

	button $base.button#6 \
		-command "tconx_slider_button left_higher $root" \
		-text Higher \
		-underline 1
	catch {
		$base.button#6 configure \
			-font -*-Helvetica-Bold-R-Normal-*-*-120-*-*-*-*-*-*
	}

	button $base.button#9 \
		-command "tconx_slider_button right_higher $root" \
		-text Higher \
		-underline 2
	catch {
		$base.button#9 configure \
			-font -*-Helvetica-Bold-R-Normal-*-*-120-*-*-*-*-*-*
	}

	button $base.button#8 \
		-command "tconx_slider_button left_set $root" \
		-text {Set value} \
		-underline 0
	catch {
		$base.button#8 configure \
			-font -*-Helvetica-Bold-R-Normal-*-*-120-*-*-*-*-*-*
	}

	button $base.button#10 \
		-command "tconx_slider_button right_set $root" \
		-text {Set value} \
		-underline 4
	catch {
		$base.button#10 configure \
			-font -*-Helvetica-Bold-R-Normal-*-*-120-*-*-*-*-*-*
	}

	button $base.button#7 \
		-command "tconx_slider_button left_lower $root" \
		-text Lower \
		-underline 0
	catch {
		$base.button#7 configure \
			-font -*-Helvetica-Bold-R-Normal-*-*-120-*-*-*-*-*-*
	}

	button $base.button#11 \
		-command "tconx_slider_button right_lower $root" \
		-text Lower \
		-underline 2
	catch {
		$base.button#11 configure \
			-font -*-Helvetica-Bold-R-Normal-*-*-120-*-*-*-*-*-*
	}

	button $base.button#12 \
		-command "tconx_slider_button set_manually $root" \
		-text {Set Manually} \
		-underline 4
	catch {
		$base.button#12 configure \
			-font -*-Helvetica-Bold-R-Normal-*-*-120-*-*-*-*-*-*
	}

	button $base.button#2 \
		-command "tconx_slider_button apply $root" \
		-text Apply \
		-underline 0
	catch {
		$base.button#2 configure \
			-font -*-Helvetica-Bold-R-Normal-*-*-120-*-*-*-*-*-*
	}

	button $base.button#3 \
		-command "tconx_slider_button close $root" \
		-text Close \
		-underline 0
	catch {
		$base.button#3 configure \
			-font -*-Helvetica-Bold-R-Normal-*-*-120-*-*-*-*-*-*
	}

	button $base.button#1 \
		-command "tconx_slider_button help $root" \
		-text Help \
		-underline 0
	catch {
		$base.button#1 configure \
			-font -*-Helvetica-Bold-R-Normal-*-*-120-*-*-*-*-*-*
	}


	# Geometry management

	grid $base.frame#2 -in $root	-row 2 -column 1  \
		-sticky nesw
	grid $base.the_frame -in $root	-row 1 -column 1  \
		-sticky nesw
	grid $base.frame#3 -in $base.the_frame	-row 1 -column 1  \
		-sticky nesw
	grid $base.frame#4 -in $base.frame#3	-row 1 -column 1  \
		-sticky nesw
	grid $base.frame#5 -in $base.frame#3	-row 1 -column 5  \
		-sticky nesw
	grid $base.label#1 -in $base.frame#3	-row 1 -column 2 
	grid $base.scale#1 -in $base.frame#3	-row 1 -column 3  \
		-sticky ew
	grid $base.label#2 -in $base.frame#3	-row 1 -column 4 
	grid $base.button#6 -in $base.frame#4	-row 1 -column 1 
	grid $base.button#9 -in $base.frame#5	-row 1 -column 1 
	grid $base.button#8 -in $base.frame#4	-row 2 -column 1 
	grid $base.button#10 -in $base.frame#5	-row 2 -column 1 
	grid $base.button#7 -in $base.frame#4	-row 3 -column 1 
	grid $base.button#11 -in $base.frame#5	-row 3 -column 1 
	grid $base.button#12 -in $base.the_frame	-row 2 -column 1 
	grid $base.button#2 -in $base.frame#2	-row 1 -column 1 
	grid $base.button#3 -in $base.frame#2	-row 1 -column 2 
	grid $base.button#1 -in $base.frame#2	-row 1 -column 4 

	# Resize behavior management

	grid rowconfigure $base.frame#2 1 -weight 0 -minsize 30
	grid columnconfigure $base.frame#2 1 -weight 0 -minsize 30
	grid columnconfigure $base.frame#2 2 -weight 0 -minsize 30
	grid columnconfigure $base.frame#2 3 -weight 1 -minsize 30
	grid columnconfigure $base.frame#2 4 -weight 0 -minsize 30

	grid rowconfigure $base.frame#3 1 -weight 0 -minsize 30
	grid columnconfigure $base.frame#3 1 -weight 0 -minsize 30
	grid columnconfigure $base.frame#3 2 -weight 0 -minsize 30
	grid columnconfigure $base.frame#3 3 -weight 1 -minsize 30
	grid columnconfigure $base.frame#3 4 -weight 0 -minsize 30
	grid columnconfigure $base.frame#3 5 -weight 0 -minsize 30

	grid rowconfigure $base.frame#4 1 -weight 0 -minsize 30
	grid rowconfigure $base.frame#4 2 -weight 1 -minsize 30
	grid rowconfigure $base.frame#4 3 -weight 0 -minsize 30
	grid columnconfigure $base.frame#4 1 -weight 0 -minsize 30

	grid rowconfigure $root 1 -weight 1 -minsize 30
	grid rowconfigure $root 2 -weight 0 -minsize 30
	grid columnconfigure $root 1 -weight 1 -minsize 30

	grid rowconfigure $base.the_frame 1 -weight 0 -minsize 30
	grid rowconfigure $base.the_frame 2 -weight 1 -minsize 8
	grid columnconfigure $base.the_frame 1 -weight 1 -minsize 30

	grid rowconfigure $base.frame#5 1 -weight 0 -minsize 30
	grid rowconfigure $base.frame#5 2 -weight 0 -minsize 30
	grid rowconfigure $base.frame#5 3 -weight 0 -minsize 30
	grid columnconfigure $base.frame#5 1 -weight 0 -minsize 30
# additional interface code
tconx_slider_init $root

# end additional interface code

}


# Allow interface to be run "stand-alone" for testing

catch {
    if [info exists embed_args] {
	# we are running in the plugin
	slider_ui .
    } else {
	# we are running in stand-alone mode
	if {$argv0 == [info script]} {
	    wm title . "Testing slider_ui"
	    slider_ui .
	}
    }
}
