#! /bin/sh
# the next line restarts using wish \
exec wish "$0" "$@"

# interface generated by SpecTcl version 1.1 from /home/davidc/Conx/conxv/src/text.ui
#   root     is the parent window for this user interface

proc text_ui {root args} {

	# this treats "." as a special case

	if {$root == "."} {
	    set base ""
	} else {
	    set base $root
	}
    
	frame $base.frame#2

	frame $base.frame#1

	text $base.text#1 \
		-height 1 \
		-width 1 \
		-xscrollcommand "$base.scrollbar#2 set" \
		-yscrollcommand "$base.scrollbar#1 set"

	scrollbar $base.scrollbar#1 \
		-command "$base.text#1 yview" \
		-orient v

	scrollbar $base.scrollbar#2 \
		-command "$base.text#1 xview" \
		-orient h

	button $base.button#1 \
		-command "destroy $root" \
		-text Close \
		-underline 0
	catch {
		$base.button#1 configure \
			-font -*-Helvetica-Bold-R-Normal-*-*-120-*-*-*-*-*-*
	}


	# Geometry management

	grid $base.frame#2 -in $root	-row 2 -column 1  \
		-sticky nesw
	grid $base.frame#1 -in $root	-row 1 -column 1  \
		-sticky nesw
	grid $base.text#1 -in $base.frame#1	-row 1 -column 1  \
		-sticky nesw
	grid $base.scrollbar#1 -in $base.frame#1	-row 1 -column 2  \
		-sticky ns
	grid $base.scrollbar#2 -in $base.frame#1	-row 2 -column 1  \
		-sticky ew
	grid $base.button#1 -in $base.frame#2	-row 1 -column 1 

	# Resize behavior management

	grid rowconfigure $base.frame#2 1 -weight 0 -minsize 30
	grid columnconfigure $base.frame#2 1 -weight 0 -minsize 157

	grid rowconfigure $root 1 -weight 1 -minsize 30
	grid rowconfigure $root 2 -weight 0 -minsize 30
	grid columnconfigure $root 1 -weight 1 -minsize 30

	grid rowconfigure $base.frame#1 1 -weight 1 -minsize 30
	grid rowconfigure $base.frame#1 2 -weight 0 -minsize 8
	grid columnconfigure $base.frame#1 1 -weight 1 -minsize 168
	grid columnconfigure $base.frame#1 2 -weight 0 -minsize 7
# additional interface code
# end additional interface code

}


# Allow interface to be run "stand-alone" for testing

catch {
    if [info exists embed_args] {
	# we are running in the plugin
	text_ui .
    } else {
	# we are running in stand-alone mode
	if {$argv0 == [info script]} {
	    wm title . "Testing text_ui"
	    text_ui .
	}
    }
}
