#!/bin/sh
# Run this after make maintainer-clean to return this directory to
# the state it was in after you checked it out from CVS.
#
# all the following are generated by runme.sh:
rm -f config.h config.h.in aclocal.m4 configure Makefile Makefile.in missing \
      mkinstalldirs install-sh stamp-h stamp-h.in ltmain.sh ltconfig libtool \
      config.guess config.sub config.log config.status config.cache \
      src/Makefile src/Makefile.in Togl/Makefile.in Togl/Makefile \
      src/Tcl/Makefile src/Tcl/Makefile.in doc/Makefile doc/Makefile.in \
      src/lcl/Makefile src/lcl/Makefile.in
